language: node_js
sudo: required
node_js:
- stable
install:
- npm ci
jobs:
    include:
    - stage: build:beta
      script: npm run verify:beta
deploy:
  provider: script
  script: ls -lh
env:
    global:
    - REPO="git@github.com:RedHatInsights/insights-chrome-build"
    - REPO_DIR="insights-chrome-build"
cache:
  directories:
    - "$HOME/.npm"
    - ".cache"
