language: node_js
sudo: required
node_js:
- stable
install:
- npm ci
jobs:
    include:
    - stage: build:stable
      if: branch IN (prod-stable, qa-stable, ci-stable)
      script: npm run verify
    - stage: build:beta
      if: branch IN (master, prod-beta, qa-beta, ci-beta)
      script: npm run verify:beta
    - stage: deploy
      script: ls -lh
env:
    global:
    - REPO="git@github.com:RedHatInsights/insights-chrome-build"
    - REPO_DIR="insights-chrome-build"
cache:
  directories:
    - "$HOME/.npm"
    - ".cache"
